import { z } from "zod";

/**
 * Case board write contract (docs/architecture/CASE_BOARD_PRD.md §7.3).
 *
 * Every change to a board — moving a bubble, drawing a link, adding a note,
 * setting a hypothesis stance — is one `BoardOp`, and every op goes through
 * `POST /cases/:id/board/ops`. The API validates with these schemas (there is
 * no global ValidationPipe), the MCP tool reuses them, and the web app derives
 * its op types from them, so the three cannot drift apart.
 *
 * Objects are strict: zod strips unknown keys by default, which silently
 * *widens* what a caller can do (a misspelt field is ignored instead of
 * refused). Strict objects fail closed.
 *
 * Ids of board-native rows (items, links) are generated by the client. That is
 * what lets an op address an item before the server has seen it, and what lets
 * undo/redo replay the same op without temp-id remapping. Creating ops are
 * idempotent on that id: replaying `item.create` for an item that was deleted
 * brings the same row back.
 */

export const BOARD_COLORS = [
  "yellow",
  "blue",
  "green",
  "pink",
  "gray",
  "red",
  "amber",
  "violet",
] as const;
export type BoardColor = (typeof BOARD_COLORS)[number];

export const BOARD_NOTE_COLORS = [
  "yellow",
  "blue",
  "green",
  "pink",
  "gray",
] as const satisfies readonly BoardColor[];

export const BOARD_HIGHLIGHT_COLORS = [
  "yellow",
  "green",
  "blue",
  "pink",
  "red",
] as const satisfies readonly BoardColor[];

/** Board-native item kinds a client may create directly. */
export const BOARD_NATIVE_KINDS = ["NOTE", "FRAME"] as const;

export const BOARD_ITEM_KINDS = [
  "EVIDENCE",
  "HYPOTHESIS",
  "COMMENT",
  "NOTE",
  "FRAME",
] as const;
export type BoardItemKind = (typeof BOARD_ITEM_KINDS)[number];

export const BOARD_LINK_CERTAINTIES = ["CONFIRMED", "SUSPECTED"] as const;
export type BoardLinkCertainty = (typeof BOARD_LINK_CERTAINTIES)[number];

export const BOARD_STANCES = ["SUPPORTS", "CONTRADICTS", "NEUTRAL"] as const;
export type BoardStance = (typeof BOARD_STANCES)[number];

/**
 * The default link vocabulary, offered first in the link popover. `kind` is
 * free-form (like `edges.relation_type`), so "Custom…" adds to it.
 */
export const BOARD_LINK_KINDS = [
  "related_to",
  "same_entity",
  "communicates_with",
  "derived_from",
  "contradicts",
  "precedes",
] as const;

export const BOARD_MAX_OPS_PER_BATCH = 200;
export const BOARD_NOTE_MAX_CHARS = 20_000;
export const BOARD_FRAME_TITLE_MAX_CHARS = 200;
export const BOARD_LINK_KIND_MAX_CHARS = 64;
export const BOARD_LINK_LABEL_MAX_CHARS = 200;
export const BOARD_HYPOTHESIS_TITLE_MAX_CHARS = 500;

/** Board coordinates are unbounded in principle; this only rejects garbage. */
const COORD_LIMIT = 10_000_000;
const SIZE_LIMIT = 20_000;

/** Any UUID-shaped string. Imported workspaces carry uuidv5 ids, so no version check. */
const Id = z.guid();
/** Finding ids come from the scanner; accept any non-empty token. */
const FindingId = z.string().min(1).max(200);
const OpId = z.string().min(1).max(100);

const Coord = z.number().finite().min(-COORD_LIMIT).max(COORD_LIMIT);
const Size = z.number().finite().positive().max(SIZE_LIMIT);
const ZIndex = z.number().int().min(-1_000_000).max(1_000_000);

export const BoardColorSchema = z.enum(BOARD_COLORS);

/** Where a link or stance attaches: an item, optionally one finding row inside it. */
export const BoardEndpointSchema = z.strictObject({
  itemId: Id,
  findingId: FindingId.optional(),
});
export type BoardEndpoint = z.infer<typeof BoardEndpointSchema>;

/**
 * Style is merged into the stored style key by key; `null` removes a key.
 * `rowHighlights` is merged per finding id the same way, so highlighting one
 * row never rewrites the others.
 */
export const BoardStyleSchema = z.strictObject({
  color: BoardColorSchema.nullable().optional(),
  highlight: BoardColorSchema.nullable().optional(),
  rowHighlights: z
    .record(FindingId, BoardColorSchema.nullable())
    .optional(),
  /** COMMENT pins anchored to one finding row inside their parent bubble. */
  anchorFindingId: FindingId.nullable().optional(),
  /**
   * EVIDENCE items: where each finding node sits, relative to its asset node.
   * Merged per finding like `rowHighlights`; `null` sends one back to its
   * default spot around the asset.
   */
  findingPositions: z
    .record(FindingId, z.strictObject({ x: Coord, y: Coord }).nullable())
    .optional(),
});
export type BoardStyle = z.infer<typeof BoardStyleSchema>;

export const BoardContentSchema = z.strictObject({
  text: z.string().max(BOARD_NOTE_MAX_CHARS).optional(),
  title: z.string().max(BOARD_FRAME_TITLE_MAX_CHARS).optional(),
});
export type BoardContent = z.infer<typeof BoardContentSchema>;

const ItemPatchSchema = z.strictObject({
  x: Coord.optional(),
  y: Coord.optional(),
  width: Size.nullable().optional(),
  height: Size.nullable().optional(),
  z: ZIndex.optional(),
  parentId: Id.nullable().optional(),
  collapsed: z.boolean().optional(),
  style: BoardStyleSchema.optional(),
  content: BoardContentSchema.optional(),
});
export type BoardItemPatch = z.infer<typeof ItemPatchSchema>;

const LinkPatchSchema = z.strictObject({
  kind: z.string().trim().min(1).max(BOARD_LINK_KIND_MAX_CHARS).optional(),
  label: z.string().max(BOARD_LINK_LABEL_MAX_CHARS).nullable().optional(),
  certainty: z.enum(BOARD_LINK_CERTAINTIES).optional(),
  confidence: z.number().min(0).max(1).nullable().optional(),
  note: z.string().max(BOARD_NOTE_MAX_CHARS).nullable().optional(),
});
export type BoardLinkPatch = z.infer<typeof LinkPatchSchema>;

/** Optimistic concurrency for text edits: the `updatedAt` the editor started from. */
const ExpectedUpdatedAt = z.iso.datetime({ offset: true }).optional();

export const BoardOpSchema = z.discriminatedUnion("type", [
  // ── Board-native items ──────────────────────────────────────────────────
  z.strictObject({
    type: z.literal("item.create"),
    opId: OpId,
    id: Id,
    kind: z.enum(BOARD_NATIVE_KINDS),
    x: Coord,
    y: Coord,
    width: Size.optional(),
    height: Size.optional(),
    z: ZIndex.optional(),
    parentId: Id.nullish(),
    style: BoardStyleSchema.optional(),
    content: BoardContentSchema.optional(),
  }),
  z.strictObject({
    type: z.literal("item.update"),
    opId: OpId,
    id: Id,
    patch: ItemPatchSchema,
    expectedUpdatedAt: ExpectedUpdatedAt,
  }),
  /**
   * Notes, frames and comment pins are soft-deleted. A hypothesis card may be
   * removed from the board too — its thread is kept and can be placed again.
   * Evidence cannot: that is `evidence.remove`, which changes the case.
   */
  z.strictObject({ type: z.literal("item.delete"), opId: OpId, id: Id }),
  z.strictObject({ type: z.literal("item.restore"), opId: OpId, id: Id }),

  // ── Links drawn on this board ───────────────────────────────────────────
  z.strictObject({
    type: z.literal("link.create"),
    opId: OpId,
    id: Id,
    source: BoardEndpointSchema,
    target: BoardEndpointSchema,
    kind: z.string().trim().min(1).max(BOARD_LINK_KIND_MAX_CHARS),
    label: z.string().max(BOARD_LINK_LABEL_MAX_CHARS).optional(),
    certainty: z.enum(BOARD_LINK_CERTAINTIES).optional(),
    confidence: z.number().min(0).max(1).optional(),
    note: z.string().max(BOARD_NOTE_MAX_CHARS).optional(),
  }),
  z.strictObject({
    type: z.literal("link.update"),
    opId: OpId,
    id: Id,
    patch: LinkPatchSchema,
    expectedUpdatedAt: ExpectedUpdatedAt,
  }),
  z.strictObject({ type: z.literal("link.delete"), opId: OpId, id: Id }),
  z.strictObject({ type: z.literal("link.restore"), opId: OpId, id: Id }),
  /** Copy a board link into the global graph (`edges`, origin MANUAL). */
  z.strictObject({ type: z.literal("link.promote"), opId: OpId, id: Id }),

  // ── Domain commands (delegate to the case services) ─────────────────────
  /**
   * Put an asset (or a finding, which brings its asset) on the board as case
   * evidence. Replaying it for an evidence item that was removed restores the
   * evidence exactly as it was, attached findings and notes included.
   */
  z.strictObject({
    type: z.literal("evidence.add"),
    opId: OpId,
    itemId: Id,
    entityType: z.enum(["asset", "finding"]),
    entityId: z.string().min(1).max(200),
    x: Coord.optional(),
    y: Coord.optional(),
  }),
  z.strictObject({ type: z.literal("evidence.remove"), opId: OpId, itemId: Id }),
  z.strictObject({
    type: z.literal("finding.attach"),
    opId: OpId,
    itemId: Id,
    findingId: FindingId,
  }),
  z.strictObject({
    type: z.literal("finding.detach"),
    opId: OpId,
    itemId: Id,
    findingId: FindingId,
  }),
  z.strictObject({
    type: z.literal("hypothesis.create"),
    opId: OpId,
    itemId: Id,
    title: z.string().trim().min(1).max(BOARD_HYPOTHESIS_TITLE_MAX_CHARS),
    x: Coord.optional(),
    y: Coord.optional(),
    color: z.string().max(32).optional(),
    /** Evidence the new hypothesis starts out supported by. */
    supports: z.array(BoardEndpointSchema).max(100).optional(),
  }),
  /**
   * Set how a piece of evidence bears on a hypothesis. A finding row that is
   * not yet attached to the case is attached first, in the same transaction.
   */
  z.strictObject({
    type: z.literal("stance.set"),
    opId: OpId,
    hypothesisItemId: Id,
    target: BoardEndpointSchema,
    stance: z.enum(BOARD_STANCES),
    weight: z.number().min(0).max(1).optional(),
    note: z.string().max(BOARD_NOTE_MAX_CHARS).optional(),
  }),
  z.strictObject({
    type: z.literal("stance.remove"),
    opId: OpId,
    hypothesisItemId: Id,
    target: BoardEndpointSchema,
  }),
  z.strictObject({
    type: z.literal("comment.create"),
    opId: OpId,
    itemId: Id,
    body: z.string().trim().min(1).max(BOARD_NOTE_MAX_CHARS),
    /** The item (or finding row) the pin sticks to; null pins it to the canvas. */
    anchor: BoardEndpointSchema.nullable(),
    x: Coord.optional(),
    y: Coord.optional(),
  }),
  z.strictObject({
    type: z.literal("comment.resolve"),
    opId: OpId,
    itemId: Id,
    resolved: z.boolean(),
  }),
  /**
   * Place an existing thread on the board: a hypothesis card that was removed
   * from it, or a discussion started elsewhere (MCP, the thread list). An
   * item the thread already has is brought back rather than duplicated.
   */
  z.strictObject({
    type: z.literal("thread.place"),
    opId: OpId,
    itemId: Id,
    threadId: Id,
    x: Coord.optional(),
    y: Coord.optional(),
    anchor: BoardEndpointSchema.nullable().optional(),
  }),
]);

export type BoardOp = z.infer<typeof BoardOpSchema>;
export type BoardOpType = BoardOp["type"];
export type BoardOpOf<T extends BoardOpType> = Extract<BoardOp, { type: T }>;

export const ApplyBoardOpsSchema = z.strictObject({
  /** Identifies the writing tab, so it can ignore the echo of its own writes. */
  clientId: z.string().min(1).max(64),
  /** The board version the client last saw; used to flag concurrent writers. */
  baseVersion: z.number().int().nonnegative(),
  ops: z.array(BoardOpSchema).min(1).max(BOARD_MAX_OPS_PER_BATCH),
});
export type ApplyBoardOps = z.infer<typeof ApplyBoardOpsSchema>;

/** Ops that only move or reshape things: coalesced on the timeline. */
export const BOARD_GEOMETRY_PATCH_KEYS = [
  "x",
  "y",
  "width",
  "height",
  "z",
  "collapsed",
  "parentId",
] as const;
