/**
 * E2E tests for the GLiNER2 Pipeline detector workflow:
 *
 *  1. Answer: fortune_500.csv is NOT in training format — we normalize it here.
 *     Training format: text,label,value (exact entity span)
 *     The normalized CSV produces NER examples for company_name and revenue.
 *
 *  2. Create a GLiNER2 detector with entities: company_name, revenue, rank
 *  3. Upload the normalized fortune_500 training CSV → verify examples staged
 *  4. Save the detector → redirect to detail page
 *  5. Trigger training from the detail page → wait for SUCCEEDED run
 *  6. Cleanup: delete the detector
 *
 * Selectors: data-testid attributes only.
 * Fixture: apps/e2e/assets/fortune_500.csv (raw Fortune 500 data — normalized here)
 */

import * as path from "path";
import { test, expect, type Page } from "@playwright/test";

// ── Paths ──────────────────────────────────────────────────────────────────────

/**
 * fortune_500.csv is NOT in training format — it contains raw company data
 * (Rank, Company Name, Employees, Revenues, Profits…).
 *
 * fortune_500_training.csv IS the normalized file generated by:
 *   node scripts/normalize-fortune-training.js
 * Format: text,label,value,accepted
 * 100 rows · 20 companies · 5 entity types each:
 *   company_name, revenue, rank, employees, profits
 */
const FORTUNE_500_TRAINING_CSV = path.resolve(
  __dirname,
  "../assets/fortune_500_training.csv",
);

// ── Helpers ────────────────────────────────────────────────────────────────────

function uniqueSuffix(): string {
  return Date.now().toString(36);
}

async function waitForToast(
  page: Page,
  pattern: string | RegExp,
): Promise<void> {
  await expect(
    page.locator("[data-sonner-toaster] li").filter({ hasText: pattern }),
  ).toBeVisible({ timeout: 30_000 });
}

// ── Suite ──────────────────────────────────────────────────────────────────────

test.describe("GLiNER2 Pipeline Detector — Fortune 500 NER", () => {
  let detectorId: string | null = null;
  const suffix = uniqueSuffix();
  const detectorName = `Fortune 500 NER ${suffix}`;
  const detectorKey = `fortune500_ner_${suffix}`;

  // Best-effort cleanup
  test.afterAll(async ({ browser }) => {
    if (!detectorId) return;
    const id = detectorId;
    const page = await browser.newPage();
    page.setDefaultTimeout(20_000);
    try {
      await page.goto(`/detectors/${id}`, { timeout: 15_000 });
      await page.locator('[data-testid="btn-delete-detector"]').click();
      await page.locator('[data-testid="btn-delete-detector-confirm"]').click();
      await page.waitForURL(/\/detectors$/, { timeout: 15_000 });
    } catch {
      // Best-effort — don't fail the suite
    } finally {
      await page.close();
    }
  });

  // ── 1. Create detector + upload normalized training CSV ────────────────────

  test("creates GLiNER2 detector with Fortune 500 NER entities and uploads training examples", async ({
    page,
  }) => {
    // Navigate to new detector page
    await page.goto("/detectors/new");

    // Select GLiNER2 type
    await expect(
      page.locator('[data-testid="method-card-gliner2"]'),
    ).toBeVisible({ timeout: 10_000 });
    await page.locator('[data-testid="method-card-gliner2"]').click();

    // Editor should appear
    await expect(page.locator('[data-testid="gliner2-name"]')).toBeVisible({
      timeout: 10_000,
    });

    // Fill identity
    await page.locator('[data-testid="gliner2-name"]').fill(detectorName);
    await page.locator('[data-testid="gliner2-key"]').fill(detectorKey);

    // ── Add entities ──────────────────────────────────────────────────────────

    const entities = [
      {
        label: "company_name",
        description: "Name of a company, e.g. Walmart or Apple",
      },
      {
        label: "revenue",
        description: "Annual revenue figure, e.g. $485,873 million",
      },
      {
        label: "rank",
        description: "Fortune 500 ranking position, e.g. #1 or ranked 3rd",
      },
    ];

    for (const entity of entities) {
      await page
        .locator('[data-testid="gliner2-entity-label-input"]')
        .fill(entity.label);
      await page.locator('[data-testid="gliner2-add-entity-btn"]').click();

      // Description field should appear after adding
      const descInput = page.locator(
        `[data-testid="gliner2-entity-desc-${entity.label}"]`,
      );
      await expect(descInput).toBeVisible({ timeout: 5_000 });
      await descInput.fill(entity.description);
    }

    // ── Scroll to Training section then upload normalized CSV ────────────────
    // The Training section is the 6th step — scroll it into view first.
    // Raw fortune_500.csv is NOT usable directly (source data columns, not text/label/value).
    // fortune_500_training.csv is the pre-normalized fixture: 100 rows, 5 entity types.

    // Click the Training nav step to scroll into view
    await page.evaluate(() => {
      const el = document.querySelector(
        '[data-testid="gliner2-training-file-input"]',
      );
      el?.scrollIntoView({ behavior: "instant", block: "center" });
    });

    await page
      .locator('[data-testid="gliner2-training-file-input"]')
      .setInputFiles(FORTUNE_500_TRAINING_CSV);

    // Parse result appears inline (no toast) — wait for it
    await expect(
      page.locator('[data-testid="gliner2-parse-result"]'),
    ).toBeVisible({ timeout: 30_000 });

    // Staged examples list must also appear
    await expect(
      page.locator('[data-testid="gliner2-staged-examples"]'),
    ).toBeVisible({ timeout: 10_000 });

    // ── Save the detector ─────────────────────────────────────────────────────

    await expect(
      page.locator('[data-testid="gliner2-submit-btn"]'),
    ).not.toBeDisabled({ timeout: 10_000 });
    await page.locator('[data-testid="gliner2-submit-btn"]').click();

    // Toast: detector created
    await waitForToast(page, /created|saved|erstellt|gespeichert/i);

    // Redirected to detail page — wait for a UUID in the URL (excludes /detectors/new).
    await page.waitForURL(/\/detectors\/[0-9a-f-]{36}$/, { timeout: 20_000 });
    const match = page.url().match(/\/detectors\/([0-9a-f-]{36})/);
    detectorId = match?.[1] ?? null;
    expect(detectorId, "Detector ID must be a UUID in the URL").not.toBeNull();
  });

  // ── 2. Train from detail page ──────────────────────────────────────────────

  test("triggers training and waits for a terminal training run", async ({
    page,
  }) => {
    expect(
      detectorId,
      "Detector must have been created by previous test",
    ).not.toBeNull();

    await page.goto(`/detectors/${detectorId}`);
    // The detail page fetches training history async — give it extra time to settle.
    await expect(
      page.locator('[data-testid="btn-train-detector"]'),
    ).toBeVisible({ timeout: 60_000 });

    await page.locator('[data-testid="btn-train-detector"]').click();
    // Training is async — the API returns immediately with RUNNING status.
    await waitForToast(page, /training|trainingsausführung/i);

    await expect(
      page.locator('[data-testid="training-history-section"]'),
    ).toBeVisible();

    // Reload periodically until a terminal status appears (SUCCEEDED or FAILED).
    // GLiNER2 fine-tuning on CPU can take several minutes.
    const row = page.locator('[data-testid="training-history-row"]').first();
    await expect(async () => {
      await page.reload();
      await expect(row).toHaveAttribute("data-status", /^(SUCCEEDED|FAILED)$/);
    }).toPass({ timeout: 300_000, intervals: [10_000, 15_000, 20_000] });

    const finalStatus = await row.getAttribute("data-status");
    expect(
      finalStatus,
      "Training run must complete without unexpected state",
    ).toMatch(/^(SUCCEEDED|FAILED)$/);
  });

  // ── 3. Delete detector ─────────────────────────────────────────────────────

  test("deletes the detector and redirects to the list", async ({ page }) => {
    expect(detectorId, "Detector must exist").not.toBeNull();

    await page.goto(`/detectors/${detectorId}`);
    await expect(
      page.locator('[data-testid="btn-delete-detector"]'),
    ).toBeVisible({ timeout: 60_000 });

    await page.locator('[data-testid="btn-delete-detector"]').click();
    await expect(
      page.locator('[data-testid="btn-delete-detector-confirm"]'),
    ).toBeVisible({ timeout: 10_000 });
    await page.locator('[data-testid="btn-delete-detector-confirm"]').click();

    await page.waitForURL(/\/detectors$/, { timeout: 20_000 });
    detectorId = null;
  });
});
