import {
  Injectable,
  Logger,
  OnModuleDestroy,
  OnModuleInit,
} from '@nestjs/common';
import {
  S3Client,
  PutObjectCommand,
  GetObjectCommand,
  DeleteObjectCommand,
  CreateBucketCommand,
  HeadBucketCommand,
  ListObjectsV2Command,
  NoSuchKey,
} from '@aws-sdk/client-s3';
import { Readable } from 'stream';
import { promises as fsp, createReadStream } from 'fs';
import * as path from 'path';
import { type LogLevel, RunnerLogEntryDto, RunnerLogsResponseDto } from './dto';

type RunnerLogStream = 'stderr' | 'stdout' | 'combined';

interface StoredRunnerLogEntry {
  timestamp: string;
  stream: RunnerLogStream;
  message: string;
}

interface StoredLogObject {
  sourceId: string;
  runnerId: string;
  key: string;
  size: number;
  lastModified: Date | null;
}

/**
 * Persistence backend for per-run NDJSON log objects.
 * Two implementations: S3-compatible object storage and the local filesystem
 * (used by the desktop app, where no object storage exists).
 */
interface LogObjectStore {
  /** Overwrite the whole object for a run with the given NDJSON content. */
  put(sourceId: string, runnerId: string, content: string): Promise<void>;
  /** Stream the object back, or null when it does not exist. */
  getStream(sourceId: string, runnerId: string): Promise<Readable | null>;
  delete(sourceId: string, runnerId: string): Promise<void>;
  list(): Promise<StoredLogObject[]>;
}

/** Resolved parameters used internally by listLogs / paginateEntries. */
interface ResolvedListParams {
  take: number;
  skip: number;
  sortOrder: 'asc' | 'desc';
  searchLower: string;
  levelFilter: Set<string>;
  streamFilter: Set<string>;
}

const SYNC_INTERVAL_MS = 5_000;

// ── S3 store ────────────────────────────────────────────────────────────────

class S3LogObjectStore implements LogObjectStore {
  constructor(
    private readonly client: S3Client,
    private readonly bucket: string,
    private readonly prefix: string,
  ) {}

  private key(sourceId: string, runnerId: string): string {
    return `${this.prefix}${sourceId}/${runnerId}.ndjson`;
  }

  async put(
    sourceId: string,
    runnerId: string,
    content: string,
  ): Promise<void> {
    await this.client.send(
      new PutObjectCommand({
        Bucket: this.bucket,
        Key: this.key(sourceId, runnerId),
        Body: Buffer.from(content, 'utf8'),
        ContentType: 'application/x-ndjson',
      }),
    );
  }

  async getStream(
    sourceId: string,
    runnerId: string,
  ): Promise<Readable | null> {
    try {
      const obj = await this.client.send(
        new GetObjectCommand({
          Bucket: this.bucket,
          Key: this.key(sourceId, runnerId),
        }),
      );
      return obj.Body as Readable;
    } catch (err: any) {
      if (
        err instanceof NoSuchKey ||
        err?.name === 'NoSuchKey' ||
        err?.$metadata?.httpStatusCode === 404
      ) {
        return null;
      }
      throw err;
    }
  }

  async delete(sourceId: string, runnerId: string): Promise<void> {
    await this.client.send(
      new DeleteObjectCommand({
        Bucket: this.bucket,
        Key: this.key(sourceId, runnerId),
      }),
    );
  }

  async list(): Promise<StoredLogObject[]> {
    const out: StoredLogObject[] = [];
    let continuationToken: string | undefined;
    do {
      const res = await this.client.send(
        new ListObjectsV2Command({
          Bucket: this.bucket,
          Prefix: this.prefix,
          ContinuationToken: continuationToken,
        }),
      );
      for (const obj of res.Contents ?? []) {
        if (!obj.Key || !obj.Key.startsWith(this.prefix)) continue;
        const rest = obj.Key.slice(this.prefix.length);
        const match = rest.match(/^(.+)\/([^/]+)\.ndjson$/);
        if (!match) continue;
        out.push({
          sourceId: match[1],
          runnerId: match[2],
          key: obj.Key,
          size: obj.Size ?? 0,
          lastModified: obj.LastModified ?? null,
        });
      }
      continuationToken = res.IsTruncated
        ? res.NextContinuationToken
        : undefined;
    } while (continuationToken);
    return out;
  }

  async ensureBucket(logger: Logger): Promise<void> {
    try {
      await this.client.send(new HeadBucketCommand({ Bucket: this.bucket }));
    } catch {
      try {
        await this.client.send(
          new CreateBucketCommand({ Bucket: this.bucket }),
        );
        logger.log(`Created S3 bucket: ${this.bucket}`);
      } catch (err: any) {
        if (err?.Code !== 'BucketAlreadyOwnedByYou') {
          logger.error(
            `Failed to create S3 bucket ${this.bucket}: ${err?.message}`,
          );
        }
      }
    }
  }
}

// ── Local filesystem store (desktop) ───────────────────────────────────────

class LocalFileLogObjectStore implements LogObjectStore {
  constructor(private readonly rootDir: string) {}

  private filePath(sourceId: string, runnerId: string): string {
    // sourceId / runnerId are UUIDs generated by the API, safe as path segments.
    return path.join(this.rootDir, sourceId, `${runnerId}.ndjson`);
  }

  async put(
    sourceId: string,
    runnerId: string,
    content: string,
  ): Promise<void> {
    const file = this.filePath(sourceId, runnerId);
    await fsp.mkdir(path.dirname(file), { recursive: true });
    // Write via temp file + rename so readers never see a half-written object.
    const tmp = `${file}.tmp`;
    await fsp.writeFile(tmp, content, 'utf8');
    await fsp.rename(tmp, file);
  }

  async getStream(
    sourceId: string,
    runnerId: string,
  ): Promise<Readable | null> {
    const file = this.filePath(sourceId, runnerId);
    try {
      await fsp.access(file);
    } catch {
      return null;
    }
    return createReadStream(file, { encoding: 'utf8' });
  }

  async delete(sourceId: string, runnerId: string): Promise<void> {
    const file = this.filePath(sourceId, runnerId);
    await fsp.rm(file, { force: true });
    await fsp.rm(`${file}.tmp`, { force: true });
    // Remove the source directory when it became empty (ignore failures).
    await fsp.rmdir(path.dirname(file)).catch(() => undefined);
  }

  async list(): Promise<StoredLogObject[]> {
    const out: StoredLogObject[] = [];
    let sourceDirs: string[];
    try {
      sourceDirs = await fsp.readdir(this.rootDir);
    } catch {
      return out;
    }
    for (const sourceId of sourceDirs) {
      const dir = path.join(this.rootDir, sourceId);
      let files: string[];
      try {
        const stat = await fsp.stat(dir);
        if (!stat.isDirectory()) continue;
        files = await fsp.readdir(dir);
      } catch {
        continue;
      }
      for (const file of files) {
        if (!file.endsWith('.ndjson')) continue;
        const full = path.join(dir, file);
        try {
          const stat = await fsp.stat(full);
          out.push({
            sourceId,
            runnerId: file.slice(0, -'.ndjson'.length),
            key: full,
            size: stat.size,
            lastModified: stat.mtime,
          });
        } catch {
          // File disappeared between readdir and stat — skip.
        }
      }
    }
    return out;
  }
}

@Injectable()
export class RunnerLogStorageService implements OnModuleInit, OnModuleDestroy {
  private readonly logger = new Logger(RunnerLogStorageService.name);

  // ── In-memory log buffers ─────────────────────────────────────────────────
  // Populated for the lifetime of an active run on this API replica.
  // Cleared on finalizeRunner / deleteRunnerLogs.
  private readonly inMemoryLogs = new Map<string, StoredRunnerLogEntry[]>();

  // Partial-line buffers (one per runnerId:stream key)
  private readonly lineBuffers = new Map<string, string>();

  // Per-run size accounting for the in-memory buffer (approximate bytes)
  private readonly bufferBytes = new Map<string, number>();
  // Number of earliest lines dropped per run once the per-run cap was hit
  private readonly droppedLines = new Map<string, number>();

  // Persistence backend (S3 or local filesystem), null = ephemeral logs
  private store: LogObjectStore | null = null;
  private storeMode: 's3' | 'local' | null = null;
  private localRootDir: string | null = null;

  // Per-run size caps (0 = disabled)
  private maxLinesPerRun = 100_000;
  private maxBytesPerRun = 50 * 1024 * 1024;
  // Total local storage cap in bytes (0 = disabled; local store only)
  private maxTotalBytes = 0;

  // Per-runner persistence sync timers (periodic snapshot during active run)
  private readonly syncTimers = new Map<string, NodeJS.Timeout>();

  // Per-runner sourceId lookup (needed by onModuleDestroy)
  private readonly runnerSourceIds = new Map<string, string>();

  /**
   * Serialized upload chain per runner.
   * Guarantees that snapshot writes never race: the next put always waits for
   * the previous one to finish, so the latest snapshot always wins.
   */
  private readonly syncChains = new Map<string, Promise<void>>();

  // ── Lifecycle ─────────────────────────────────────────────────────────────

  async onModuleInit(): Promise<void> {
    this.maxLinesPerRun = this.readIntEnv(
      'RUNNER_LOG_MAX_LINES_PER_RUN',
      100_000,
    );
    this.maxBytesPerRun =
      this.readIntEnv('RUNNER_LOG_MAX_MB_PER_RUN', 50) * 1024 * 1024;

    const localDir = process.env.RUNNER_LOG_DIR;
    const bucket = process.env.S3_BUCKET;

    if (localDir) {
      this.localRootDir = path.resolve(localDir);
      await fsp
        .mkdir(this.localRootDir, { recursive: true })
        .catch((err: any) => {
          this.logger.error(
            `Could not create RUNNER_LOG_DIR ${this.localRootDir}: ${err?.message}`,
          );
        });
      this.store = new LocalFileLogObjectStore(this.localRootDir);
      this.storeMode = 'local';
      this.maxTotalBytes =
        this.readIntEnv('RUNNER_LOG_MAX_TOTAL_MB', 2048) * 1024 * 1024;
      this.logger.log(
        `Local filesystem log storage: dir=${this.localRootDir} ` +
          `perRunCap=${Math.round(this.maxBytesPerRun / 1024 / 1024)}MB/${this.maxLinesPerRun} lines ` +
          `totalCap=${Math.round(this.maxTotalBytes / 1024 / 1024)}MB`,
      );
      return;
    }

    if (!bucket) {
      this.logger.warn(
        'Neither RUNNER_LOG_DIR nor S3_BUCKET is set — runner logs will be streamed in real time but not persisted after the run completes.',
      );
      return;
    }

    const endpoint = process.env.S3_ENDPOINT;
    const region = process.env.S3_REGION || 'us-east-1';
    const forcePathStyle = process.env.S3_FORCE_PATH_STYLE !== 'false';

    const client = new S3Client({
      region,
      ...(endpoint ? { endpoint } : {}),
      forcePathStyle,
      credentials:
        process.env.S3_ACCESS_KEY_ID && process.env.S3_SECRET_ACCESS_KEY
          ? {
              accessKeyId: process.env.S3_ACCESS_KEY_ID,
              secretAccessKey: process.env.S3_SECRET_ACCESS_KEY,
            }
          : undefined,
    });

    const s3Store = new S3LogObjectStore(
      client,
      bucket,
      process.env.S3_LOG_PREFIX || 'runner-logs/',
    );

    await this.retryWithBackoff(
      () => s3Store.ensureBucket(this.logger),
      10,
      1000,
      `S3 bucket ${bucket}`,
    );

    this.store = s3Store;
    this.storeMode = 's3';
    this.logger.log(
      `S3 log storage: bucket=${bucket} endpoint=${endpoint || 'aws'}`,
    );
  }

  async onModuleDestroy(): Promise<void> {
    // Final snapshot for any active runners before process shuts down
    if (this.store) {
      await Promise.all(
        Array.from(this.syncTimers.keys()).map(async (runnerId) => {
          const sourceId = this.runnerSourceIds.get(runnerId);
          if (!sourceId) return;
          try {
            await this.syncSerialized(sourceId, runnerId);
          } catch (err: any) {
            this.logger.warn(
              `Final log sync failed for ${runnerId}: ${err?.message}`,
            );
          }
        }),
      );
    }

    for (const timer of this.syncTimers.values()) {
      clearInterval(timer);
    }
    this.syncTimers.clear();
    this.runnerSourceIds.clear();
    this.syncChains.clear();
  }

  // ── Public API ────────────────────────────────────────────────────────────

  /** True when log persistence (S3 or local filesystem) is configured. */
  get isPersistenceEnabled(): boolean {
    return this.store !== null;
  }

  /**
   * List every persisted log object.
   * Used by the nightly cleanup job to detect orphaned logs (objects whose
   * runner row no longer exists). Returns an empty list when persistence is
   * disabled.
   */
  async listStoredLogObjects(): Promise<StoredLogObject[]> {
    if (!this.store) return [];
    return this.store.list();
  }

  /** Returns the sourceId recorded at initializeRunner time, or undefined if unknown. */
  getRunnerSourceId(runnerId: string): string | undefined {
    return this.runnerSourceIds.get(runnerId);
  }

  async initializeRunner(sourceId: string, runnerId: string): Promise<void> {
    this.inMemoryLogs.set(runnerId, []);
    this.bufferBytes.set(runnerId, 0);
    this.droppedLines.delete(runnerId);
    this.clearRunnerBuffers(runnerId);
    this.syncChains.delete(runnerId);

    if (this.store) {
      this.runnerSourceIds.set(runnerId, sourceId);
      this.startSyncTimer(sourceId, runnerId);
      // Immediately create an empty object so the key exists in storage
      await this.doSync(sourceId, runnerId).catch(() => undefined);
    }
  }

  /**
   * Parse a raw output chunk into complete log lines and append them to
   * the in-memory buffer.  Returns the new `RunnerLogEntryDto` objects so
   * callers can push them to WebSocket clients without a separate read.
   */
  appendChunk(
    runnerId: string,
    chunk: string,
    stream: RunnerLogStream = 'stderr',
  ): RunnerLogEntryDto[] {
    if (!chunk) return [];

    const bufferKey = this.getBufferKey(runnerId, stream);
    const previous = this.lineBuffers.get(bufferKey) || '';
    const combined = previous + chunk;
    const lines = combined.split('\n');
    const remainder = lines.pop() || '';
    this.lineBuffers.set(bufferKey, remainder);

    if (lines.length === 0) return [];

    const entries: StoredRunnerLogEntry[] = lines.map((line) =>
      this.createEntry(line.replace(/\r$/, ''), stream),
    );

    const buffer = this.inMemoryLogs.get(runnerId);
    if (buffer) {
      const baseIndex = buffer.length;
      this.pushEntries(runnerId, buffer, entries);
      return entries.map((e, i) => this.entryToDto(e, baseIndex + i));
    }

    // Runner not initialised on this replica — return DTOs with ephemeral index
    return entries.map((e, i) => this.entryToDto(e, i));
  }

  /**
   * Append entries while enforcing the per-run caps: when the buffer grows
   * beyond maxLinesPerRun / maxBytesPerRun, the earliest lines are dropped
   * (the tail is what matters for diagnosing a run) and the drop is counted
   * so a truncation notice can be surfaced to readers.
   */
  private pushEntries(
    runnerId: string,
    buffer: StoredRunnerLogEntry[],
    entries: StoredRunnerLogEntry[],
  ): void {
    let bytes = this.bufferBytes.get(runnerId) ?? 0;
    for (const entry of entries) {
      bytes += this.approxEntryBytes(entry);
    }
    buffer.push(...entries);

    let dropped = 0;
    while (
      buffer.length > 0 &&
      ((this.maxLinesPerRun > 0 && buffer.length > this.maxLinesPerRun) ||
        (this.maxBytesPerRun > 0 && bytes > this.maxBytesPerRun))
    ) {
      const removed = buffer.shift()!;
      bytes -= this.approxEntryBytes(removed);
      dropped++;
    }

    this.bufferBytes.set(runnerId, Math.max(0, bytes));
    if (dropped > 0) {
      this.droppedLines.set(
        runnerId,
        (this.droppedLines.get(runnerId) ?? 0) + dropped,
      );
    }
  }

  private approxEntryBytes(entry: StoredRunnerLogEntry): number {
    // message + JSON envelope overhead (timestamp, stream, punctuation)
    return entry.message.length + 64;
  }

  /** Synthetic first entry describing how many earliest lines were dropped. */
  private truncationEntry(runnerId: string): StoredRunnerLogEntry | null {
    const dropped = this.droppedLines.get(runnerId);
    if (!dropped) return null;
    return {
      timestamp: new Date().toISOString(),
      stream: 'combined',
      message: `[log truncated] ${dropped.toLocaleString()} earliest lines were discarded because this run exceeded the per-run log size cap.`,
    };
  }

  async finalizeRunner(sourceId: string, runnerId: string): Promise<void> {
    // Flush any incomplete last line held in the line buffers
    for (const stream of [
      'stderr',
      'stdout',
      'combined',
    ] as RunnerLogStream[]) {
      const bufferKey = this.getBufferKey(runnerId, stream);
      const remainder = this.lineBuffers.get(bufferKey);
      if (remainder?.trim().length) {
        const entry = this.createEntry(remainder.replace(/\r$/, ''), stream);
        const buffer = this.inMemoryLogs.get(runnerId);
        if (buffer) this.pushEntries(runnerId, buffer, [entry]);
      }
      this.lineBuffers.delete(bufferKey);
    }

    if (this.store) {
      // Stop periodic syncs, then perform a final serialised snapshot so
      // there is no race between the timer and this final write.
      this.stopSyncTimer(runnerId);
      await this.syncSerialized(sourceId, runnerId);
      this.syncChains.delete(runnerId);
    }

    // Always clear in-memory state; without persistence logs are ephemeral.
    this.inMemoryLogs.delete(runnerId);
    this.bufferBytes.delete(runnerId);
    this.droppedLines.delete(runnerId);

    // Enforce the total local-disk cap in the background (local store only).
    if (this.storeMode === 'local' && this.maxTotalBytes > 0) {
      void this.enforceTotalStorageCap().catch((err: any) => {
        this.logger.warn(`Log storage cap enforcement failed: ${err?.message}`);
      });
    }
  }

  async deleteRunnerLogs(sourceId: string, runnerId: string): Promise<void> {
    this.inMemoryLogs.delete(runnerId);
    this.bufferBytes.delete(runnerId);
    this.droppedLines.delete(runnerId);
    this.clearRunnerBuffers(runnerId);

    if (this.store) {
      this.stopSyncTimer(runnerId);
      this.syncChains.delete(runnerId);
      await this.store.delete(sourceId, runnerId).catch((err) => {
        this.logger.warn(
          `Could not delete stored log for ${runnerId}: ${err?.message}`,
        );
      });
    }
  }

  async listLogs(params: {
    sourceId: string;
    runnerId: string;
    cursor?: string;
    skip?: number;
    take?: number | string;
    search?: string;
    levels?: string[];
    sortOrder?: 'asc' | 'desc';
    streams?: string[];
  }): Promise<RunnerLogsResponseDto> {
    const resolved = this.resolveListParams(params);

    // ── Active run on this replica (in-memory) ─────────────────────────────
    const buffer = this.inMemoryLogs.get(params.runnerId);
    if (buffer !== undefined) {
      const truncation = this.truncationEntry(params.runnerId);
      const all = truncation ? [truncation, ...buffer] : buffer;
      const dtos = all.map((e, i) => this.entryToDto(e, i));
      return this.paginateEntries(params.runnerId, dtos, resolved);
    }

    // ── Persisted (completed run or different replica) ─────────────────────
    if (this.store) {
      const stream = await this.store.getStream(
        params.sourceId,
        params.runnerId,
      );
      if (!stream) return this.emptyResponse(params.runnerId, resolved.take);
      const allEntries = await this.readAllEntriesFromStream(stream);
      return this.paginateEntries(params.runnerId, allEntries, resolved);
    }

    // No persistence configured and no active in-memory run.
    return this.emptyResponse(params.runnerId, resolved.take);
  }

  // ── Pagination helper ─────────────────────────────────────────────────────

  private paginateEntries(
    runnerId: string,
    allEntries: RunnerLogEntryDto[],
    params: ResolvedListParams,
  ): RunnerLogsResponseDto {
    const { take, skip, sortOrder, searchLower, levelFilter, streamFilter } =
      params;

    const filtered = allEntries.filter((e) =>
      this.matchesFilter(e, searchLower, levelFilter, streamFilter),
    );
    const total = filtered.length;

    if (sortOrder === 'desc') {
      filtered.reverse();
    }

    const page = filtered.slice(skip, skip + take);
    const nextSkip = skip + take;
    const hasMore = nextSkip < total;

    return {
      runnerId,
      entries: page,
      nextCursor: hasMore ? `i:${nextSkip}` : null,
      cursor: `i:${nextSkip}`,
      hasMore,
      take,
      total,
    };
  }

  // ── Persistence sync helpers ──────────────────────────────────────────────

  /**
   * Schedule a snapshot write that is chained after the previous one for this
   * runner.  This prevents concurrent puts from racing.
   */
  private syncSerialized(sourceId: string, runnerId: string): Promise<void> {
    const prev = this.syncChains.get(runnerId) ?? Promise.resolve();
    const next = prev
      .then(() => this.doSync(sourceId, runnerId))
      .catch((err: any) => {
        this.logger.warn(`Log sync failed for ${runnerId}: ${err?.message}`);
      });
    this.syncChains.set(runnerId, next);
    return next;
  }

  /** Serialise the in-memory buffer and write it as a single object. */
  private async doSync(sourceId: string, runnerId: string): Promise<void> {
    if (!this.store) return;
    const entries = this.inMemoryLogs.get(runnerId);
    if (entries === undefined) return; // Already finalized or not on this replica
    const truncation = this.truncationEntry(runnerId);
    const all = truncation ? [truncation, ...entries] : entries;
    const ndjson = all.map((e) => this.encodeEntry(e)).join('');
    await this.store.put(sourceId, runnerId, ndjson);
  }

  private startSyncTimer(sourceId: string, runnerId: string): void {
    this.runnerSourceIds.set(runnerId, sourceId);
    const timer = setInterval(() => {
      void this.syncSerialized(sourceId, runnerId);
    }, SYNC_INTERVAL_MS);
    this.syncTimers.set(runnerId, timer);
  }

  private stopSyncTimer(runnerId: string): void {
    const timer = this.syncTimers.get(runnerId);
    if (timer) {
      clearInterval(timer);
      this.syncTimers.delete(runnerId);
    }
    this.runnerSourceIds.delete(runnerId);
  }

  // ── Total local-disk cap ──────────────────────────────────────────────────

  /**
   * Keep the local log directory under RUNNER_LOG_MAX_TOTAL_MB by deleting
   * the oldest completed-run log files first. Files of currently active
   * runners are never deleted.
   */
  private async enforceTotalStorageCap(): Promise<void> {
    if (!this.store || this.storeMode !== 'local' || this.maxTotalBytes <= 0) {
      return;
    }
    const objects = await this.store.list();
    let total = objects.reduce((sum, o) => sum + o.size, 0);
    if (total <= this.maxTotalBytes) return;

    const active = new Set(this.inMemoryLogs.keys());
    const deletable = objects
      .filter((o) => !active.has(o.runnerId))
      .sort(
        (a, b) =>
          (a.lastModified?.getTime() ?? 0) - (b.lastModified?.getTime() ?? 0),
      );

    for (const obj of deletable) {
      if (total <= this.maxTotalBytes) break;
      try {
        await this.store.delete(obj.sourceId, obj.runnerId);
        total -= obj.size;
        this.logger.log(
          `Deleted old runner log ${obj.runnerId} (${Math.round(obj.size / 1024)}KB) to stay under the local log storage cap.`,
        );
      } catch (err: any) {
        this.logger.warn(
          `Could not delete log ${obj.runnerId} during cap enforcement: ${err?.message}`,
        );
      }
    }
  }

  // ── Stream parser (for persisted reads) ──────────────────────────────────

  private async readAllEntriesFromStream(
    readable: Readable,
  ): Promise<RunnerLogEntryDto[]> {
    const entries: RunnerLogEntryDto[] = [];
    let remainder = '';
    let index = 0;

    for await (const rawChunk of readable) {
      const chunk: string =
        typeof rawChunk === 'string'
          ? rawChunk
          : (rawChunk as Buffer).toString('utf8');
      remainder += chunk;

      while (true) {
        const nl = remainder.indexOf('\n');
        if (nl === -1) break;

        const rawLine = remainder.slice(0, nl);
        remainder = remainder.slice(nl + 1);

        if (!rawLine) continue;
        entries.push(this.decodeEntryAtIndex(rawLine, index++));
      }
    }

    if (remainder) {
      entries.push(this.decodeEntryAtIndex(remainder, index));
    }

    return entries;
  }

  // ── Filtering ─────────────────────────────────────────────────────────────

  private matchesFilter(
    entry: RunnerLogEntryDto,
    searchLower: string,
    levelFilter: Set<string>,
    streamFilter: Set<string>,
  ): boolean {
    if (searchLower && !entry.message.toLowerCase().includes(searchLower))
      return false;
    if (levelFilter.size > 0 && !levelFilter.has(entry.level)) return false;
    if (streamFilter.size > 0 && !streamFilter.has(entry.stream)) return false;
    return true;
  }

  // ── Level / display inference ─────────────────────────────────────────────

  private inferLevel(stream: RunnerLogStream, message: string): LogLevel {
    const structured = this.tryParseJson(message);
    if (structured) {
      const raw = structured['level'] ?? structured['severity'];
      if (typeof raw === 'string') {
        const normalized = this.normalizeLevel(raw);
        if (normalized !== 'UNKNOWN') return normalized;
      }
    }

    const prefixed = this.matchLevelPrefix(message);
    if (prefixed !== 'UNKNOWN') return prefixed;

    // A Python traceback carries no level token but is unambiguously an error.
    if (/^\s*Traceback \(most recent call last\)/m.test(message))
      return 'ERROR';

    // Deliberately NOT `stream === 'stderr' ? 'ERROR' : 'UNKNOWN'`. Python's
    // logging writes every level to stderr, and libraries print progress bars
    // and advisory notices there too, so the stream says nothing about
    // severity. Treating it as ERROR is what buried real failures under model
    // download progress and OpenCV warnings, making the ERROR count useless.
    return 'UNKNOWN';
  }

  /**
   * Read a level only where a logger would actually put one: at the start of
   * the line, or in the level field of a common timestamped format.
   *
   * The previous free-text scan matched the first level word anywhere in the
   * message, so "no error found" was an ERROR and a path containing "debug"
   * was DEBUG.
   */
  private matchLevelPrefix(message: string): LogLevel {
    const LEVEL = '(TRACE|DEBUG|INFO|WARNING|WARN|ERROR|FATAL|CRITICAL)';

    // The CLI's own format: "INFO:src.pipeline: message" (see main.py's
    // basicConfig), plus the common "[INFO]" / "INFO -" / "INFO:" variants.
    const leading = message.match(
      new RegExp(`^\\s*\\[?${LEVEL}\\]?\\s*[:\\-|\\s]`, 'i'),
    );
    if (leading?.[1]) return this.normalizeLevel(leading[1]);

    // Timestamped: "2026-07-15 10:00:00,123 - name - INFO - message".
    const timestamped = message.match(
      new RegExp(
        `^\\s*\\d{4}-\\d{2}-\\d{2}[T ][\\d:.,]+\\s*[-|]?\\s*[^-|]*[-|]\\s*${LEVEL}\\b`,
        'i',
      ),
    );
    if (timestamped?.[1]) return this.normalizeLevel(timestamped[1]);

    return 'UNKNOWN';
  }

  private normalizeLevel(raw: string): LogLevel {
    switch (raw.toUpperCase()) {
      case 'TRACE':
        return 'TRACE';
      case 'DEBUG':
        return 'DEBUG';
      case 'INFO':
        return 'INFO';
      case 'WARN':
      case 'WARNING':
        return 'WARN';
      case 'ERROR':
        return 'ERROR';
      case 'FATAL':
      case 'CRITICAL':
        return 'FATAL';
      default:
        return 'UNKNOWN';
    }
  }

  private tryParseJson(message: string): Record<string, unknown> | null {
    const trimmed = message.trim();
    if (!trimmed.startsWith('{') || !trimmed.endsWith('}')) return null;
    try {
      const parsed = JSON.parse(trimmed) as unknown;
      if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
        return parsed as Record<string, unknown>;
      }
      return null;
    } catch {
      return null;
    }
  }

  private inferDisplayMessage(
    structured: Record<string, unknown> | null,
    rawMessage: string,
  ): string {
    const msg = structured?.['message'] ?? structured?.['msg'];
    if (typeof msg === 'string' && msg.trim().length > 0) return msg.trim();
    return rawMessage.trim();
  }

  // ── Entry encoding / decoding ─────────────────────────────────────────────

  private createEntry(
    message: string,
    stream: RunnerLogStream,
  ): StoredRunnerLogEntry {
    return { timestamp: new Date().toISOString(), stream, message };
  }

  private encodeEntry(entry: StoredRunnerLogEntry): string {
    return `${JSON.stringify(entry)}\n`;
  }

  /** Convert a stored entry + its position index to a DTO. */
  private entryToDto(
    entry: StoredRunnerLogEntry,
    index: number,
  ): RunnerLogEntryDto {
    const structured = this.tryParseJson(entry.message);
    return {
      cursor: String(index),
      timestamp: entry.timestamp,
      stream: entry.stream,
      message: this.inferDisplayMessage(structured, entry.message),
      level: this.inferLevel(entry.stream, entry.message),
    };
  }

  private decodeEntryAtIndex(
    rawLine: string,
    index: number,
  ): RunnerLogEntryDto {
    try {
      const parsed = JSON.parse(rawLine) as Partial<StoredRunnerLogEntry>;
      const stream = this.normalizeStream(parsed.stream);
      const timestamp =
        typeof parsed.timestamp === 'string' ? parsed.timestamp : null;
      const rawMessage =
        typeof parsed.message === 'string'
          ? parsed.message
          : JSON.stringify(parsed);
      const structured = this.tryParseJson(rawMessage);
      return {
        cursor: String(index),
        timestamp,
        stream,
        message: this.inferDisplayMessage(structured, rawMessage),
        level: this.inferLevel(stream, rawMessage),
      };
    } catch {
      return {
        cursor: String(index),
        timestamp: null,
        stream: 'combined',
        message: rawLine,
        level: 'UNKNOWN',
      };
    }
  }

  private normalizeStream(value: unknown): RunnerLogStream {
    if (value === 'stderr' || value === 'stdout' || value === 'combined')
      return value;
    return 'combined';
  }

  // ── Cursor / param resolution ─────────────────────────────────────────────

  private resolveListParams(params: {
    cursor?: string;
    skip?: number;
    take?: number | string;
    search?: string;
    levels?: string[];
    streams?: string[];
    sortOrder?: 'asc' | 'desc';
  }): ResolvedListParams {
    const take = this.resolveTake(params.take);
    const sortOrder = params.sortOrder === 'desc' ? 'desc' : 'asc';
    const searchLower = params.search?.trim().toLowerCase() ?? '';
    const levelFilter = new Set(
      (params.levels ?? []).map((l) => l.toUpperCase()),
    );
    const streamFilter = new Set(
      (params.streams ?? []).map((s) => s.toLowerCase()),
    );

    // `skip` takes precedence over cursor
    let skip = 0;
    if (typeof params.skip === 'number' && params.skip >= 0) {
      skip = params.skip;
    } else if (params.cursor) {
      skip = this.parseIndexCursor(params.cursor);
    }

    return { take, skip, sortOrder, searchLower, levelFilter, streamFilter };
  }

  private parseIndexCursor(cursor?: string): number {
    if (!cursor) return 0;
    if (cursor.startsWith('i:')) {
      const n = Number.parseInt(cursor.slice(2), 10);
      return Number.isFinite(n) && n >= 0 ? n : 0;
    }
    // Legacy byte-cursor: treat as start-of-file (index 0)
    return 0;
  }

  private resolveTake(take?: number | string): number {
    const numeric =
      typeof take === 'string' ? Number.parseInt(take, 10) : Number(take);
    const resolved = Number.isFinite(numeric) ? numeric : 200;
    return Math.max(1, Math.min(1000, Math.trunc(resolved)));
  }

  private emptyResponse(runnerId: string, take: number): RunnerLogsResponseDto {
    return {
      runnerId,
      entries: [],
      nextCursor: null,
      cursor: 'i:0',
      hasMore: false,
      take,
      total: 0,
    };
  }

  private readIntEnv(name: string, fallback: number): number {
    const raw = process.env[name];
    if (raw === undefined || raw === '') return fallback;
    const parsed = Number.parseInt(raw, 10);
    return Number.isFinite(parsed) && parsed >= 0 ? parsed : fallback;
  }

  // ── Retry helper ──────────────────────────────────────────────────────────

  private async retryWithBackoff<T>(
    operation: () => Promise<T>,
    maxRetries: number,
    baseDelayMs: number,
    description: string,
  ): Promise<T> {
    let lastError: Error | undefined;
    for (let attempt = 0; attempt <= maxRetries; attempt++) {
      try {
        return await operation();
      } catch (err: any) {
        lastError = err;
        if (attempt === maxRetries) break;
        const delay = baseDelayMs * 2 ** attempt;
        this.logger.warn(
          `${description} not ready (attempt ${attempt + 1}/${maxRetries + 1}): ${err?.message}. Retrying in ${delay}ms...`,
        );
        await new Promise((resolve) => setTimeout(resolve, delay));
      }
    }
    throw new Error(
      `${description} unavailable after ${maxRetries + 1} attempts: ${lastError?.message}`,
    );
  }

  private clearRunnerBuffers(runnerId: string) {
    for (const key of this.lineBuffers.keys()) {
      if (key.startsWith(`${runnerId}:`)) this.lineBuffers.delete(key);
    }
  }

  private getBufferKey(runnerId: string, stream: RunnerLogStream): string {
    return `${runnerId}:${stream}`;
  }
}
