import { app, Menu, Tray, nativeImage, type MenuItemConstructorOptions } from 'electron';
import type { NamespaceRuntime } from './namespace-runtime.js';
import type { NamespaceManager } from './namespace-manager.js';
import type { SettingsManager } from './settings-manager.js';
import type { UpdateChecker } from './update-checker.js';

// System tray / macOS menu-bar item. Lets the app keep running with the
// window closed: shows workspaces (running ones marked), switches/opens them,
// and exposes update + background-mode controls.
//
// Icons are embedded as base64 so no extra file has to survive packaging.
// macOS gets a monochrome template image (auto-adapts to menu-bar theme);
// generated by a funnel-glyph script, black + alpha only.
const TRAY_TEMPLATE_16 =
  'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAXUlEQVR42mNgGCwgAIj/k4gDkA3YT4YB+6nqAqoCBSB2wIEVCGl2IMLpDvgMaCDCgAZ8BggQiJH9UDX0AQ5Q5zYQ8jeumEB3vgIpBhhgMcCAVFc0QANtP6GQpwgAAGtLTfk1hqByAAAAAElFTkSuQmCC';
const TRAY_TEMPLATE_32 =
  'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAxUlEQVR42mNgGAWDFBgAsQOVsQGxFt8H4v80wvfxOUQAiN/T0HIYfg+1CwMk0MFyGE7A5oACOjqgAJsDFOgYBQq40kECjR3xHlfwowMHGuFRQBYQgKbaBhJxAa78TmqR/J7CRGdAiQPWUyHlr6fEAdTKfmSD81Sw/DwlDgigggMCKE2IIAP2k4kDRguRYQkUcJQP6/FVs9Qslt+T09yiFiCm2ZZASwc0EOGABlr3Fwg5wIDW6aBhoHyPHhLo9b/BaAFBDgAAGo49aDwys3QAAAAASUVORK5CYII=';

function buildTrayIcon(): Electron.NativeImage {
  if (process.platform === 'darwin') {
    const image = nativeImage.createFromBuffer(Buffer.from(TRAY_TEMPLATE_16, 'base64'), {
      scaleFactor: 1,
    });
    image.addRepresentation({
      buffer: Buffer.from(TRAY_TEMPLATE_32, 'base64'),
      scaleFactor: 2,
    });
    image.setTemplateImage(true);
    return image;
  }
  // Windows/Linux trays are colored; reuse the 32px glyph (theme-agnostic
  // enough on dark and light trays since it ships with alpha).
  return nativeImage.createFromBuffer(Buffer.from(TRAY_TEMPLATE_32, 'base64'));
}

export interface TrayDeps {
  runtime: NamespaceRuntime;
  namespaceManager: NamespaceManager;
  settingsManager: SettingsManager;
  updateChecker: UpdateChecker;
  showWindow: () => void;
  quit: () => void;
}

export class AppTray {
  private tray: Tray | null = null;

  constructor(private deps: TrayDeps) {}

  create(): void {
    if (this.tray) return;
    this.tray = new Tray(buildTrayIcon());
    this.tray.setToolTip('Classifyre');
    // Windows: single left-click restores the window (menu stays on right-click).
    this.tray.on('click', () => {
      if (process.platform === 'win32') this.deps.showWindow();
    });
    this.rebuildMenu();
    this.deps.runtime.onStateChange(() => this.rebuildMenu());
    this.deps.updateChecker.onStatus(() => this.rebuildMenu());
  }

  rebuildMenu(): void {
    if (!this.tray) return;
    const { runtime, namespaceManager, settingsManager, updateChecker, showWindow, quit } = this.deps;

    const activeId = runtime.getActiveTabId();
    const namespaceItems: MenuItemConstructorOptions[] = namespaceManager
      .list()
      .map((ns) => {
        const isRunning = runtime.isOpen(ns.id);
        return {
          label: ns.name,
          type: 'checkbox' as const,
          checked: isRunning,
          sublabel: isRunning ? (ns.id === activeId ? 'Running · active' : 'Running') : undefined,
          click: () => {
            showWindow();
            // Open() switches to the tab when already running.
            runtime.open(ns.id).catch((err) => console.error(`[tray] open ${ns.name} failed:`, err));
          },
        };
      });

    const updateItems: MenuItemConstructorOptions[] = [];
    const status = updateChecker.getStatus();
    if (status.status === 'ready' || status.status === 'manual-ready') {
      updateItems.push({
        label: status.status === 'ready' ? `Restart to Update to ${status.version}` : `Install Update ${status.version}…`,
        click: () => updateChecker.restartAndInstall(),
      });
    } else if (status.status === 'downloading') {
      updateItems.push({
        label: status.percent === null ? 'Downloading update…' : `Downloading update… ${status.percent}%`,
        enabled: false,
      });
    } else if (status.status === 'available') {
      updateItems.push({
        label: `Download Update ${status.version}`,
        click: () => void updateChecker.downloadUpdate(),
      });
    } else {
      updateItems.push({
        label: 'Check for Updates…',
        click: () => void updateChecker.checkForUpdates(),
      });
    }

    const menu = Menu.buildFromTemplate([
      { label: 'Show Classifyre', click: showWindow },
      { label: 'Workspaces Home', click: () => { showWindow(); runtime.showSelector(); } },
      { type: 'separator' },
      ...(namespaceItems.length > 0
        ? [...namespaceItems, { type: 'separator' } as MenuItemConstructorOptions]
        : []),
      ...updateItems,
      {
        label: 'Keep Running in Background',
        type: 'checkbox',
        checked: settingsManager.get().runInBackground,
        click: (item) => {
          settingsManager.update({ runInBackground: item.checked });
        },
      },
      {
        label: 'Desktop Notifications',
        type: 'checkbox',
        checked: settingsManager.get().desktopNotifications,
        click: (item) => {
          settingsManager.update({ desktopNotifications: item.checked });
        },
      },
      { type: 'separator' },
      { label: `Quit Classifyre (${app.getVersion()})`, click: quit },
    ]);
    this.tray.setContextMenu(menu);
  }

  destroy(): void {
    this.tray?.destroy();
    this.tray = null;
  }
}
