{{- if and .Values.frontend.enabled .Values.frontend.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "classifyre.web.fullname" . }}
  labels:
    {{- include "classifyre.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  minAvailable: {{ .Values.frontend.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "classifyre.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
{{- end }}
